/**
 * Press Center Events: department upcoming events + AI posting plan.
 * Stored in localStorage (key: pio_events). Client-only.
 */

const STORAGE_KEY = "pio_events"

export type PioEventPost = {
  id: string
  /** Campaign slot key when generated by SaferU event prompts */
  key?: string
  /** ISO date (YYYY-MM-DD) when this message should go out */
  postDate: string
  /** Suggested clock time e.g. "10:00 AM" */
  postTime?: string
  /** Short label e.g. "About 30 days before", "Day of event" */
  timingLabel: string
  /** Human-readable campaign stage returned by the strategist */
  campaignStage?: string
  /** Why SaferU recommends this campaign stage */
  strategicPurpose?: string
  /** Code-calculated relationship between posting and event time */
  timeUntilEvent?: string
  channel: "Facebook" | "X" | "Nextdoor" | "Email" | "Website"
  postTitle?: string
  message: string
  callToAction?: string
  suggestedImage?: string
  detailsToVerify?: string[]
  qualityStatus?: "approved" | "needs_human_review"
  tag?: string
}

export type PioEvent = {
  id: string
  title: string
  description: string
  location: string
  /** ISO date (YYYY-MM-DD) */
  eventDate: string
  startTime: string
  endTime?: string
  eventType?: string
  category?: string
  address?: string
  highlights?: string[]
  contactEmail?: string
  contactPhone?: string
  recurring?: boolean
  audienceGoals?: string
  contentPrefs?: string
  /** hosting | co_hosting | promoting | participating */
  hostingRole?: string
  hostOrganization?: string
  /** Who the event is for (e.g. Families, Residents) */
  audience?: string
  parking?: string
  registration?: string
  registrationRequired?: boolean
  registrationDeadline?: string
  registrationUrl?: string
  cost?: string
  accessibility?: string
  arrivalInstructions?: string
  website?: string
  primaryImage?: string
  additionalAssets?: string
  capacityStatus?: string
  weatherPlan?: string
  /** Private staff notes — not used in AI posts */
  internalNotes?: string
  status?: "draft" | "generated" | "cancelled" | "rescheduled"
  /** Why the event was cancelled — used for cancellation posts */
  cancellationReason?: string
  /** Previous date when rescheduled */
  previousEventDate?: string
  posts: PioEventPost[]
  createdAt: string
  updatedAt: string
}

export function mergeEventPosts(
  existing: PioEventPost[],
  incoming: PioEventPost[]
): PioEventPost[] {
  const byIdentity = new Map<string, PioEventPost>()
  const withoutKey: PioEventPost[] = []

  function identity(p: PioEventPost): string | null {
    if (!p.key) return null
    return `${p.key}:${p.channel || "Facebook"}`
  }

  for (const p of existing) {
    const id = identity(p)
    if (id) byIdentity.set(id, p)
    else withoutKey.push(p)
  }
  for (const p of incoming) {
    const id = identity(p)
    if (id) byIdentity.set(id, p)
    else withoutKey.push(p)
  }
  return [...withoutKey, ...byIdentity.values()].sort((a, b) =>
    a.postDate.localeCompare(b.postDate)
  )
}

export function formatEventDateLong(isoDate: string): string {
  const d = new Date(isoDate + "T00:00:00")
  if (Number.isNaN(d.getTime())) return isoDate
  return d.toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  })
}

export function formatTimeRange(startTime?: string, endTime?: string): string {
  const fmt = (t: string) => {
    const m24 = t.match(/^(\d{1,2}):(\d{2})$/)
    if (m24) {
      const h = Number(m24[1])
      const min = m24[2]
      const ampm = h >= 12 ? "PM" : "AM"
      const h12 = h % 12 || 12
      return `${h12}:${min} ${ampm}`
    }
    return t
  }
  if (!startTime && !endTime) return ""
  if (startTime && endTime) return `${fmt(startTime)} – ${fmt(endTime)}`
  return fmt(startTime || endTime || "")
}

export function mapsSearchUrl(location: string, address?: string): string {
  const q = [location, address].filter(Boolean).join(", ")
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`
}

function getStorage(): PioEvent[] {
  if (typeof window === "undefined") return []
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return []
    const parsed = JSON.parse(raw) as PioEvent[]
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

function setStorage(items: PioEvent[]): void {
  if (typeof window === "undefined") return
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items))
  } catch {
    // ignore
  }
}

export function getPioEvents(): PioEvent[] {
  return getStorage().sort(
    (a, b) => new Date(a.eventDate).getTime() - new Date(b.eventDate).getTime()
  )
}

/** Upcoming events from today forward (inclusive). */
export function getUpcomingPioEvents(): PioEvent[] {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  return getPioEvents().filter((e) => {
    const d = new Date(e.eventDate + "T00:00:00")
    return d.getTime() >= today.getTime()
  })
}

export function getPioEventById(id: string): PioEvent | null {
  return getStorage().find((e) => e.id === id) ?? null
}

export function savePioEvent(event: PioEvent): PioEvent {
  const all = getStorage()
  const idx = all.findIndex((e) => e.id === event.id)
  const next = { ...event, updatedAt: new Date().toISOString() }
  if (idx >= 0) all[idx] = next
  else all.push(next)
  setStorage(all)
  return next
}

export function deletePioEvent(id: string): void {
  setStorage(getStorage().filter((e) => e.id !== id))
}

export function daysUntil(eventDate: string): number {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const d = new Date(eventDate + "T00:00:00")
  return Math.round((d.getTime() - today.getTime()) / (24 * 60 * 60 * 1000))
}

/** Flattened posts across events, sorted by post date ascending. */
export function getScheduledEventPosts(opts?: {
  from?: string
  to?: string
}): Array<PioEventPost & { eventId: string; eventTitle: string }> {
  const from = opts?.from
  const to = opts?.to
  const rows: Array<PioEventPost & { eventId: string; eventTitle: string }> = []
  for (const event of getPioEvents()) {
    for (const post of event.posts) {
      if (from && post.postDate < from) continue
      if (to && post.postDate > to) continue
      rows.push({ ...post, eventId: event.id, eventTitle: event.title })
    }
  }
  return rows.sort((a, b) => a.postDate.localeCompare(b.postDate))
}

export function formatEventDateShort(isoDate: string): { month: string; day: string } {
  const d = new Date(isoDate + "T00:00:00")
  return {
    month: d.toLocaleString("en-US", { month: "short" }).toUpperCase(),
    day: String(d.getDate()).padStart(2, "0"),
  }
}
